[package]
name = "task-jefe-stub"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = { path = "../../sys/userlib" }

[features]
no-panic = ["userlib/no-panic"]

[[bin]]
name = "task-jefe-stub"
test = false
doctest = false
bench = false

[lints]
workspace = true
